name: Atualizar PIX Doutores

on:
  schedule:
    # Roda a cada hora das 6h às 22h (horário de Brasília = UTC-3)
    - cron: '0 9-01 * * 1-6'   # Segunda a Sábado, 06h-22h BRT
  workflow_dispatch:             # Também pode rodar manualmente no GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps chromium

      - name: Rodar scraper
        env:
          SISTEMA_USER: ${{ secrets.SISTEMA_USER }}
          SISTEMA_PASS: ${{ secrets.SISTEMA_PASS }}
        run: |
          cd scripts
          python scraper.py

      - name: Salvar dados.json no repositório
        run: |
          git config user.name  "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add scripts/dados.json
          git diff --staged --quiet || git commit -m "🔄 Atualizar dados PIX - $(date +'%d/%m/%Y %H:%M')"
          git push
